#!/bin/sh
#
# ~/.xinitrc.d/gnome-keyring
#
# allow ssh password caching
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID
